config/routes.rb
Hpvideos::Application.routes.draw do

	devise_for :users
	root to: "attachments#index"
	resources :users, :only => [:index, :update]
	resources :categories, :only => [:show]
	resources :attachments
	resources :favourites 

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

	has_attached_file :attachment,
		styles:  	lambda { |a| a.instance.is_image? ? {:small => "x200>", :medium => "x300>", :large => "x400>"}  : {:thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10}, :medium => { :geometry => "300x300#", :format => 'jpg', :time => 10}}},
		:processors => lambda { |a| a.is_video? ? [ :ffmpeg ] : [ :thumbnail ] }
		
	has_and_belongs_to_many :categories, :class_name => 'Category'
	
	
	def self.category(id)
		joins(:categories).where('`categories`.`id` = ?', id)
	end
	
	def is_video?
		attachment.instance.attachment_content_type =~ %r(video)
	end

	def is_image?
		attachment.instance.attachment_content_type =~ %r(image)
	end
	
end

app/models/category.rb
class Category < ActiveRecord::Base
	
	has_and_belongs_to_many :attachments, :class_name => 'Attachment'

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base

	has_and_belongs_to_many :users
end

app/models/slug.rb
# Stores slugs used to prettify URLs. For more information, see the
# {Slugalicious} mixin.
#
# As new slugs are created, old ones are marked as inactive and kept around for
# redirect purposes. Once a slug is old enough, it is deleted and its value can
# be used for new records (no longer redirects).
#
# Associations
# ============
#
# |             |                                       |
# |:------------|:--------------------------------------|
# | `sluggable` | The record that this slug references. |
#
# Properties
# ==========
#
# |          |                                                                                                  |
# |:---------|:-------------------------------------------------------------------------------------------------|
# | `slug`   | The slug, lowercased and normalized. Slugs must be unique to their `sluggable_type` and `scope`. |
# | `active` | Whether this is the most recently generated slug for the sluggable.                              |
# | `scope`  | Freeform data scoping this slug to a certain subset of records within the model.                 |

class Slug < ActiveRecord::Base
  belongs_to :sluggable, polymorphic: true

  scope :for, ->(object_or_type, object_id=nil) {
    object_type = object_id ? object_or_type : object_or_type.class.to_s
    object_id ||= object_or_type.id
    where(sluggable_type: object_type, sluggable_id: object_id)
  }
  scope :for_class, ->(model) { where(sluggable_type: model.to_s) }
  scope :from_slug, ->(klass, scope, slug) {
    where(sluggable_type: klass.to_s, slug: slug, scope: scope)
  }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  validates :sluggable_type,
            presence: true
  validates :sluggable_id,
            presence: true,
            numericality: { only_integer: true }
  validates :slug,
            presence: true,
            length: { maximum: 126 },
            uniqueness: { case_sensitive: false, scope: [ :scope, :sluggable_type ] }
  validates :scope,
            length: { maximum: 126 },
            allow_nil: true
  validate :one_active_slug_per_object

  after_save :invalidate_cache
  after_destroy :invalidate_cache

  # Marks a slug as active and deactivates all other slugs assigned to the
  # record.

  def activate!
    self.class.transaction do
      Slug.for(sluggable_type, sluggable_id).update_all(active: false)
      update_column :active, true
    end
  end

  private

  def one_active_slug_per_object
    return unless new_record? or (active? and active_changed?)
    errors.add(:active, :one_per_sluggable) if active? and Slug.active.for(sluggable_type, sluggable_id).count > 0
  end

  def invalidate_cache
    Rails.cache.delete "Slug/#{sluggable_type}/#{sluggable_id}/slug"
    Rails.cache.delete "Slug/#{sluggable_type}/#{sluggable_id}/slug_with_path"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
 devise :database_authenticatable, :registerable,
    :recoverable, :rememberable
	
	has_attached_file :image, :styles => {:small => "x200>", :medium => "x300>", :large => "x400>"}
	has_and_belongs_to_many :favourites
	
	#Slugalicious
	include Slugalicious
	slugged ->(user) { "#{user.email}" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

	def index
		@attachments = Attachment.all
	end
	
	def new 
		@attachment = Attachment.new
	end
	
	def create
		@attachment = Attachment.new(upload_params)
		@attachment.save
		
		redirect_to root_path
	end
	
	def show
		@attachment = Attachment.find(params[:id])
	end
	
	def destroy
		
	end

	private
	def upload_params
		params.require(:attachment).permit(:title, :attachment)
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def show
		@attachments = Attachment.category(params[:id])
		render 'attachments/index'
	end

end

app/controllers/catergories_controller.rb
class CatergoriesController < ApplicationController
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

	before_filter :authenticate_user!

	def update
		@user = User.find(current_user.id)
		
		if (!@user.attachments.where(:id => params[:id]).present?)
			@user.attachments << Post.find(params[:id])
			@user.attchments.build
		end
		
		redirect_to_users_path
	end	
	
	def delete
		@user = User.find(current_user.id)
		@user.attachment.delete(params[:id])
		redirect_to_users_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!
	
	def index
		@user = User.find(current_user.id)
	end
	
	def update
	
		if (!User.exists?(params[:id]))
			@user = User.find_from_slug(params[:id])
		else
			@user = User.find(params[:id])		
		end
		
		@user.update(params[:user].permit(:image))
		redirect_to users_path
	end
	
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	def index
		@videos = Video.all
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
	
	#Categories
	def categories
		return Category.all
	end


end

app/helpers/catergories_helper.rb
module CatergoriesHelper
end

app/helpers/favourite_helper.rb
module FavouriteHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/attachments/index.html.erb
<div class="maincontainer" id="masonry-container" class="clearfix">
	<% @attachments.each do |i| %>
		<div class="box col3 item">
			<div class="favourites_button">Favourites
			</div>
				<%= link_to "#{i.attachment.url(:original)}", :rel => "shadowbox", :class => "divbox" do %>
					<%= image_tag(i.attachment.url(:medium), data: {"lightbox" => i.id}) %>
					<% if defined?(i.title) && !i.title.blank? %>
						<div class="caption"><%= i.title %></div>
					<% end %>
				<% end %>
		</div>
	<% end %>
</div>

app/views/attachments/new.html.erb
<%= form_for :attachment, :html => {:multipart => true}, :method => :post, url: attachments_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :attachment %><br>
		<%= f.file_field :attachment %>
		
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/attachments/show.html.erb
<%= image_tag @image.image.url %>

app/views/categories/index.html.erb
<div class="maincontainer" id="masonry-container" class="clearfix">
	<% @images.each do |i| %>
		<div class="box col3 item">
		<%= link_to "#{i.image.url(:original)}", :rel => "shadowbox" do %>
			<%= image_tag(i.image.url(:medium), data: {"lightbox" => i.id}) %>
			<% if defined?(i.title) && !i.title.blank? %>
				<div class="caption"><%= i.title %></div>
			<% end %>
		<% end %>
		</div>
	<% end %>
</div>

app/views/categories/videos.html.erb
<div class="maincontainer" id="masonry-container" class="clearfix">
	<% @images.each do |i| %>
		<div class="box col3 item">
		<%= link_to "#{i.image.url(:original)}", :rel => "shadowbox" do %>
			<%= image_tag(i.image.url(:medium), data: {"lightbox" => i.id}) %>
			<% if defined?(i.title) && !i.title.blank? %>
				<div class="caption"><%= i.title %></div>
			<% end %>
		<% end %>
		</div>
	<% end %>
</div>

app/views/elements/_footer.html.erb
<div class="modal" id="sign_in">
	<%= render :file => "devise/sessions/new" %>
</div>	

<div class="modal" id="sign_up">
	<%= render :file => "devise/registrations/new" %>
</div>

app/views/elements/_nav_bar.html.erb
	<% if user_signed_in? %>
		<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "sign_out" %>
		<%= link_to "Upload", "#button", :rel => "leanModal", :class => "upload" %>
		<%= link_to "Profile", users_path, :method => :get, :class => "profile" %>
		<%= link_to "Home", root_path, :method => :get, :class => "home" %>
	<% else %>
		<%= link_to "Sign Up", "#sign_up", :rel => "leanModal", :class => "sign_up" %>
		<%= link_to "Sign In", "#sign_in", :rel => "leanModal", :class => "sign_in" %>
	<% end %>

app/views/elements/_new.html.erb
<div class="modal" id="button">
	<%= render :file => "attachments/new", :locals => {:attachment => @attachments} %>
</div>

app/views/elements/_subnav.html.erb
<div class="subnav">
	<% categories.each do |category| %>
		<%= link_to category.name.humanize, category_path(category.id) %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hpvideos</title>
  <%= stylesheet_link_tag  "application", "profile", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="topnavbar">
		<%= render :partial => 'elements/nav_bar' %>
	</div>
</div>
<div class="subnav">
	<%= render :partial => 'elements/subnav' %>
</div>

<%= yield %>
	<%= render :partial => "elements/new" %>
	<%= render :partial => "elements/footer" %>

</body>
</html>

app/views/users/index.html.erb
<div class="profilecontainer">
	<div class="profilephoto">
		<%= image_tag(@user.image.url(:small), :width => "230") if defined?(@user.image) %>
	</div>
	<div class="profilepic">
		<%= form_for @user do |f| %>
			<%= f.file_field :image %>
			<%= f.submit "go mofo" %>
		<% end %>
	</div>
	<table class="favourited_pics">dfhtrhrt</table>
</div>


app/views/users/show.html.erb
<%= image_tag @user.image.url(:small) %>

app/views/videos/index.html.erb
<div class="maincontainer" id="masonry-container" class="clearfix">
	<% @videos.each do |v| %>
	<% end %>

app/views/videos/new.html.erb
<% form_for @video, :html => { :multipart => true } do |f| %>
	<%= f.file_field :source %>
<% end %>